apiVersion: v1
kind: ConfigMap
metadata:
  name: gancio-env
data:
  # Gancio 2.0 environment variables
  # BASEURL: "https://events.techwerkers.nl/"
  # HOST: "0.0.0.0"
  # PORT: "13120"
  # LOG_LEVEL: debug
  # #LOG_PATH: 
  # DB_DIALECT: sqlite
  # DB_STORAGE: /data/gancio.sqlite
  # DB_LOGGING: "false"
  # USER_LOCALE: /data/user_locale
  # UPLOAD_PATH: /data/uploads
  # #PROXY_PROTOCOL: 
  # #PROXY_HOSTNAME: 
  # #PROXY_PORT: 
  # #PROXY_HEADERS: 
  # #PROXY_AUTH_USERNAME: 
  # #PROXY_AUTH_PASSWORD: 
  # ALLOW_ACCESS_TO_HIDDEN_SERVICE: "false"
  DB: sqlite
