---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: gancio
spec:
  gatewayClassName: traefik
  listeners:
  - name: websecure
    port: 8443
    protocol: HTTPS
    hostname: events.techwerkers.nl
    tls:
      mode: Terminate
      certificateRefs:
      - name: gancio-tls
        namespace: gancio
