apiVersion: v1
kind: Secret
metadata:
    name: gancio-env
type: Opaque
stringData:
    NUXT_SESSION_PASSWORD: ENC[AES256_GCM,data:NfMC4mJ1cvr1TvlEy8yOd3xRk7f+lQc+R7XzySkPruuvxU+NsOilsEHQHVVW88eBNrTUZgcg2WiRzNlp6Rj8RA==,iv:Ub1Ny04Ri2ZJq8XZwAiulhbn0dbGKjQvXQXY3HDM44k=,tag:5DLeksw72dRT878FBB1hxw==,type:str]
    NUXT_SESSION_COOKIE_SECURE: ENC[AES256_GCM,data:IuZ647K96Vi/YK/fzV3ZSCwJRpBjgTFmsLV2i8MyzX+fDK6WQXrmWhLAKtxRE+7z3SU/zhuqPCXqDyLv1a9lhQ==,iv:L7V3/+Gi9FooHGvIO/ASvWaAx3O0jfSDvDDxPzPeITo=,tag:uMDVtyZtf2QcbGLSLQTfcw==,type:str]
sops:
    age:
        - recipient: age1uu9uughvqte75n94w6equ5ak40tw646k9487y32eh32ygnx3c9kseznu9c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzam5CMWhrT3g2eWpyVEFW
            VlNrK3VYM0J4RS95THcyVzdHS1lqU3I4QkRvCk03ZjZjQWxYcldXa2JhVVdDMzNi
            UHhaRUJqekxzTy9SYjBTVUpELzFTTVkKLS0tIHdGZFpkeisxZk1DK2xuK2ZnMmE2
            YlR6d2JIeTZxRE5kZGllenh1MnBudXMK5aUj2dSMOTr+t4vHqj3NJBewq+1Ika4N
            w6/Ylq0K1LuQQZILGjt+6zUzW/Jqcks8GXJKy0IXG7T2gCbS74lEYQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-30T08:45:40Z"
    mac: ENC[AES256_GCM,data:jZWiz7ZJYGJsJouDNoMGp2/v99WU6LTK/+DqzpN+URqVl3sMcXyrqVANZWiakW8lC9JC6YbXNV78cIlvbauxI58ECK1QIpGQo5DBb20cmjVJa+vDNNt3fixZ3xmZh/eWlJCmHcmISgcOWJKnE2dAasXvcR+iiACSDV/eyQh4Cl8=,iv:ooB7RAh+e/b4jasXiWYjSCuelzce2S6JRK8wLki/Kbs=,tag:mIWwG0y1SqIYIiFIedRLIA==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.11.0
